4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [1]:
def convert_units(conversion_type, value):
    """
    Converts a value between different units of measurement.

    Parameters:
    conversion_type (str): Type of conversion (e.g., 'm_to_ft', 'kg_to_lbs')
    value (float): The value to convert

    Returns:
    float: The converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172


print("Choose Conversion Type")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

choice = input("Enter choice (1-6): ")

try:
    value = float(input("Enter value to convert: "))

    if choice == "1":
        result = convert_units("m_to_ft", value)
    elif choice == "2":
        result = convert_units("ft_to_m", value)
    elif choice == "3":
        result = convert_units("kg_to_lbs", value)
    elif choice == "4":
        result = convert_units("lbs_to_kg", value)
    elif choice == "5":
        result = convert_units("l_to_gal", value)
    elif choice == "6":
        result = convert_units("gal_to_l", value)
    else:
        print("Invalid conversion type")
        result = None

    if result is not None:
        print("Converted value:", result)

except ValueError:
    print("Error: Please enter a valid numeric value.")

Choose Conversion Type
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6): 2
Enter value to convert: 5.6
Converted value: 1.7068799453798416


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [3]:
def find_sum(numbers):
    """Returns the sum of numbers in a list."""
    return sum(numbers)


def find_average(numbers):
    """Returns the average of numbers in a list."""
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """Returns the maximum value in a list."""
    return max(numbers)


def find_min(numbers):
    """Returns the minimum value in a list."""
    return min(numbers)


print("Choose an operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

choice = input("Enter your choice (1-4): ")

numbers_input = input("Enter numbers separated by spaces: ")

try:
    numbers = list(map(float, numbers_input.split()))

    if len(numbers) == 0:
        raise ValueError

    if choice == "1":
        result = find_sum(numbers)

    elif choice == "2":
        result = find_average(numbers)

    elif choice == "3":
        result = find_max(numbers)

    elif choice == "4":
        result = find_min(numbers)

    else:
        print("Invalid operation")
        result = None

    if result is not None:
        print("Result:", result)

except ValueError:
    print("Error: Please enter valid numbers.")

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 60 20
Result: 40.0


4.2 Exercise on List Manipulation

1. Extract Every Other Element
Write a Python function extract_every_other(lst) that returns every other element from a list starting from the first element.
Example: Input [1, 2, 3, 4, 5, 6] → Output [1, 3, 5].

2. Slice a Sublist
Write a Python function get_sublist(lst, start, end) that returns a sublist from index start to end (inclusive).
Example: Input [1, 2, 3, 4, 5, 6], start=2, end=4 → Output [3, 4, 5].

3. Reverse a List Using Slicing
Write a Python function reverse_list(lst) that returns the reversed list using slicing.
Example: Input [1, 2, 3, 4, 5] → Output [5, 4, 3, 2, 1].

4. Remove the First and Last Elements
Write a Python function remove_first_last(lst) that returns a list without the first and last elements using slicing.
Example: Input [1, 2, 3, 4, 5] → Output [2, 3, 4].

5. Get the First n Elements
Write a Python function get_first_n(lst, n) that returns the first n elements of a list using slicing.
Example: Input [1, 2, 3, 4, 5], n=3 → Output [1, 2, 3].

6. Extract Elements from the End
Write a Python function get_last_n(lst, n) that returns the last n elements of a list using slicing.
Example: Input [1, 2, 3, 4, 5], n=2 → Output [4, 5].

7. Extract Elements in Reverse Order
Write a Python function reverse_skip(lst) that returns elements in reverse order starting from the second-to-last element, skipping one element each time.
Example: Input [1, 2, 3, 4, 5, 6] → Output [5, 3, 1].

In [6]:
# =========================================
# 1. Extract Every Other Element
# =========================================
def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first element.

    Parameters:
    lst (list): Input list

    Returns:
    list: A new list containing every other element
    """
    return lst[::2]


# =========================================
# 2. Slice a Sublist
# =========================================
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from index 'start' to 'end' (inclusive).

    Parameters:
    lst (list): Input list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end + 1]


# =========================================
# 3. Reverse a List Using Slicing
# =========================================
def reverse_list(lst):
    """
    Returns the reversed version of the list using slicing.

    Parameters:
    lst (list): Input list

    Returns:
    list: Reversed list
    """
    return lst[::-1]


# =========================================
# 4. Remove First and Last Elements
# =========================================
def remove_first_last(lst):
    """
    Removes the first and last elements of the list.

    Parameters:
    lst (list): Input list

    Returns:
    list: List without first and last elements
    """
    return lst[1:-1]


# =========================================
# 5. Get First n Elements
# =========================================
def get_first_n(lst, n):
    """
    Returns the first n elements of a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to extract

    Returns:
    list: First n elements of the list
    """
    return lst[:n]


# =========================================
# 6. Get Last n Elements
# =========================================
def get_last_n(lst, n):
    """
    Returns the last n elements of a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to extract from the end

    Returns:
    list: Last n elements of the list
    """
    return lst[-n:]


# =========================================
# 7. Extract Elements in Reverse Order
# =========================================
def reverse_skip(lst):
    """
    Returns elements in reverse order starting from the second-to-last element,
    skipping one element in between.

    Parameters:
    lst (list): Input list

    Returns:
    list: New list with elements in reverse skip order
    """
    return lst[-2::-2]


# =========================================
# Example Usage
# =========================================
sample_list = [1, 2, 3, 4, 5, 6]

print("Original List:", sample_list)
print("Every other element:", extract_every_other(sample_list))
print("Sublist (2 to 4):", get_sublist(sample_list, 2, 4))
print("Reversed list:", reverse_list(sample_list))
print("Without first and last:", remove_first_last(sample_list))
print("First 3 elements:", get_first_n(sample_list, 3))
print("Last 2 elements:", get_last_n(sample_list, 2))
print("Reverse skip:", reverse_skip(sample_list))

Original List: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Sublist (2 to 4): [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


4.3 Exercise on Nested List
1. Flatten a Nested List

    Write a function flatten(lst) that converts a nested list into a single list.

    Example: [[1,2],[3,4],[5]] → [1,2,3,4,5]

2. Access Nested Element

    Write a function access_nested_element(lst, indices) that returns an element from a nested list using given indices.
    Example: indices=[1,2] → 6

3. Sum of Nested List

    Write a function sum_nested(lst) that returns the sum of all elements in a nested list.

4. Remove Specific Element

Write a function remove_element(lst, elem) that removes all occurrences of an element from a nested list.

5. Find Maximum Element

    Write a function find_max(lst) that returns the maximum element in a nested list.

6. Count Occurrences

    Write a function count_occurrences(lst, elem) that counts how many times an element appears in a nested list.

7. Deep Flatten

    Write a function deep_flatten(lst) that flattens a deeply nested list into one list.

8. Nested List Average

    Write a function average_nested(lst) that returns the average of all elements in a nested list.

In [9]:

# ----------------------------------------
# Task 1: Flatten a Nested List (1 level)
# ----------------------------------------
def flatten(lst):
    """Flattens a nested list (1-level deep)."""
    flat_list = []
    for sublist in lst:
        flat_list.extend(sublist)
    return flat_list

# Example
nested_list_1 = [[1, 2], [3, 4], [5]]
print("Task 1 - Flatten:", flatten(nested_list_1))


# ----------------------------------------
# Task 2: Accessing Nested List Elements
# ----------------------------------------
def access_nested_element(lst, indices):
    """Access element in nested list using a list of indices."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

# Example
nested_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices_2 = [1, 2]
print("Task 2 - Access element:", access_nested_element(nested_list_2, indices_2))


# ----------------------------------------
# Task 3: Sum of All Elements in a Nested List
# ----------------------------------------
def sum_nested(lst):
    """Recursively sum all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Example
nested_list_3 = [[1, 2], [3, [4, 5]], 6]
print("Task 3 - Sum nested:", sum_nested(nested_list_3))


# ----------------------------------------
# Task 4: Remove Specific Element from a Nested List
# ----------------------------------------
def remove_element(lst, elem):
    """Recursively remove all occurrences of elem from nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

# Example
nested_list_4 = [[1, 2], [3, 2], [4, 5]]
elem_4 = 2
print("Task 4 - Remove element:", remove_element(nested_list_4, elem_4))


# ----------------------------------------
# Task 5: Find the Maximum Element in a Nested List
# ----------------------------------------
def find_max(lst):
    """Recursively find the maximum element in nested list."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

# Example
nested_list_5 = [[1, 2], [3, [4, 5]], 6]
print("Task 5 - Find max:", find_max(nested_list_5))


# ----------------------------------------
# Task 6: Count Occurrences of an Element in a Nested List
# ----------------------------------------
def count_occurrences(lst, elem):
    """Recursively count occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example
nested_list_6 = [[1, 2], [2, 3], [2, 4]]
elem_6 = 2
print("Task 6 - Count occurrences:", count_occurrences(nested_list_6, elem_6))


# ----------------------------------------
# Task 7: Flatten a List of Lists of Lists (deep flatten)
# ----------------------------------------
def deep_flatten(lst):
    """Recursively flatten nested lists of any depth."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

# Example
nested_list_7 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print("Task 7 - Deep flatten:", deep_flatten(nested_list_7))


# ----------------------------------------
# Task 8: Nested List Average
# ----------------------------------------
def average_nested(lst):
    """Calculate the average of all elements in a nested list."""
    total = sum_nested(lst)
    count = count_elements(lst)
    return total / count if count != 0 else 0

def count_elements(lst):
    """Helper function to count all numeric elements in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_elements(item)
        else:
            count += 1
    return count

# Example
nested_list_8 = [[1, 2], [3, 4], [5, 6]]
print("Task 8 - Average nested:", average_nested(nested_list_8))

Task 1 - Flatten: [1, 2, 3, 4, 5]
Task 2 - Access element: 6
Task 3 - Sum nested: 21
Task 4 - Remove element: [[1], [3], [4, 5]]
Task 5 - Find max: 6
Task 6 - Count occurrences: 3
Task 7 - Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Task 8 - Average nested: 3.5


# 10 To - Do - NumPy
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [10]:
import numpy as np

In [11]:

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Task 1 - Empty array 2x2:\n", empty_array)

# Task 2: Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("Task 2 - All ones array 4x2:\n", ones_array)


# Task 3: Return a new array of given shape and type, filled with a fill valu (Example: shape=(3,3), fill_value=7, dtype=int)
fill_value = 7
shape = (3, 3)
filled_array = np.full(shape, fill_value, dtype=int)
print("Task 3 - Filled array 3x3 with 7:\n", filled_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
existing_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(existing_array)
print("Task 4 - Zeros like existing array:\n", zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(existing_array)
print("Task 5 - Ones like existing array:\n", ones_like_array)

# Task 6: Convert a list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("Task 6 - Numpy array from list:\n", array_from_list)

Task 1 - Empty array 2x2:
 [[2.07932599e-315 0.00000000e+000]
 [2.05522864e-306 7.95751304e-312]]
Task 2 - All ones array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Task 3 - Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Task 4 - Zeros like existing array:
 [[0 0 0]
 [0 0 0]]
Task 5 - Ones like existing array:
 [[1 1 1]
 [1 1 1]]
Task 6 - Numpy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [13]:

# Task 1 - Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Task 1 - Array 10 to 49:\n", array_10_49, "\n")

# Task 2 - Create a 3x3 matrix with values ranging from 0 to 8
matrix_0_8 = np.arange(9).reshape(3, 3)
print("Task 2 - 3x3 matrix 0-8:\n", matrix_0_8, "\n")

# Task 3 - Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Task 3 - 3x3 identity matrix:\n", identity_matrix, "\n")

# Task 4 - Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_random_array = random_array_30.mean()
# Round values for cleaner display
print("Task 4 - Random array of size 30 (rounded to 2 decimals):")
print(np.round(random_array_30, 2))
print("Mean of the array: {:.3f}\n".format(mean_random_array))

# Task 5 - Create a 10x10 array with random values and find min and max
random_array_10x10 = np.random.random((10, 10))
min_val = random_array_10x10.min()
max_val = random_array_10x10.max()
print("Task 5 - 10x10 random array (rounded to 2 decimals):")
print(np.round(random_array_10x10, 2))
print("Minimum value:", round(min_val, 3))
print("Maximum value:", round(max_val, 3), "\n")

# Task 6 - Create a zero array of size 10 and replace 5th element with 1
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1
print("Task 6 - Zero array with 5th element as 1:\n", zero_array_10, "\n")

# Task 7 - Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Task 7 - Reversed array:\n", reversed_arr, "\n")

# Task 8 - Create a 2D array with 1 on border and 0 inside
size = 5
border_array = np.ones((size, size))
border_array[1:-1, 1:-1] = 0
print("Task 8 - 2D array with border 1 and inside 0:\n", border_array, "\n")

# Task 9 - Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Task 9 - 8x8 Checkerboard pattern:\n", checkerboard)

Task 1 - Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Task 2 - 3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Task 3 - 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Task 4 - Random array of size 30 (rounded to 2 decimals):
[0.78 0.34 0.47 0.28 0.39 0.56 0.22 0.79 0.86 0.99 0.99 0.43 0.84 0.26
 0.13 1.   0.66 0.9  0.94 0.37 0.34 0.24 0.63 0.23 0.26 0.99 0.86 0.72
 0.89 0.59]
Mean of the array: 0.598

Task 5 - 10x10 random array (rounded to 2 decimals):
[[0.94 0.84 0.5  0.11 0.89 0.79 0.24 0.97 0.2  0.21]
 [0.36 0.97 0.33 0.56 0.19 0.33 0.56 0.29 0.75 0.91]
 [0.63 0.14 0.91 0.92 0.81 0.29 0.19 0.36 0.34 0.08]
 [0.89 0.26 0.74 0.29 0.32 0.51 0.83 0.31 0.13 0.32]
 [0.51 0.54 0.38 0.07 0.88 0.73 0.08 0.32 0.87 0.21]
 [0.87 0.76 0.52 0.08 0.57 0.26 0.36 0.87 0.34 0.21]
 [0.36 0.36 0.66 0.75 0.12 0.83 0.79 0.43 0.19 0.16]
 [0.4  0.14 0.22 0.83 0.9  0.02 0.25 0.79 0.28 0.49]
 [0.77 0

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [14]:

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1 - Add the two arrays x + y
add_xy = x + y
print("Task 1 - x + y:\n", add_xy, "\n")

# Task 2 - Subtract the two arrays x - y
sub_xy = x - y
print("Task 2 - x - y:\n", sub_xy, "\n")

# Task 3 - Multiply the array x with an integer (e.g., 3)
mul_x = x * 3
print("Task 3 - x * 3:\n", mul_x, "\n")

# Task 4 - Find the square of each element of x
square_x = x**2
print("Task 4 - Square of each element in x:\n", square_x, "\n")

# Task 5 - Dot products
dot_vw = np.dot(v, w)  # v · w (1D vectors)
dot_xv = np.dot(x, v)  # x · v (matrix · vector)
dot_xy = np.dot(x, y)  # x · y (matrix · matrix)
print("Task 5 - Dot product v·w:", dot_vw)
print("Task 5 - Dot product x·v:\n", dot_xv)
print("Task 5 - Dot product x·y:\n", dot_xy, "\n")

# Task 6 - Concatenate x and y along row (axis=0) and v and w along column (axis=1)
concat_xy_row = np.concatenate((x, y), axis=0)  # rows stacked
concat_vw_col = np.column_stack((v, w))  # column-wise stacking
print("Task 6 - Concatenate x and y along rows:\n", concat_xy_row)
print("Task 6 - Concatenate v and w along columns:\n", concat_vw_col, "\n")

# Task 7 - Concatenate x and v
try:
    concat_xv = np.concatenate((x, v))
    print("Task 7 - Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Task 7 - Error when concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D vector (length 2). Shapes are incompatible for concatenation along axis=0 (2x2 vs 2,). To concatenate, v must be reshaped to a 2x1 or 1x2 matrix to match x’s dimensions.")

Task 1 - x + y:
 [[ 6  8]
 [10 13]] 

Task 2 - x - y:
 [[-4 -4]
 [-4 -3]] 

Task 3 - x * 3:
 [[ 3  6]
 [ 9 15]] 

Task 4 - Square of each element in x:
 [[ 1  4]
 [ 9 25]] 

Task 5 - Dot product v·w: 219
Task 5 - Dot product x·v:
 [29 77]
Task 5 - Dot product x·y:
 [[19 22]
 [50 58]] 

Task 6 - Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Task 6 - Concatenate v and w along columns:
 [[ 9 11]
 [10 12]] 

Task 7 - Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 matrix and v is a 1D vector (length 2). Shapes are incompatible for concatenation along axis=0 (2x2 vs 2,). To concatenate, v must be reshaped to a 2x1 or 1x2 matrix to match x’s dimensions.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT
.
• Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


In [15]:

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1 - Prove A * A^-1 = I
A_inv = np.linalg.inv(A)  # Inverse of A
identity = np.dot(A, A_inv)  # Matrix multiplication A * A^-1
print("Task 1 - A * A^-1:\n", np.round(identity, 3))
print("Check if identity:\n", np.allclose(identity, np.eye(2)), "\n")  # True if approx identity

# Task 2 - Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("Task 2 - AB:\n", AB)
print("Task 2 - BA:\n", BA)
print("Check if AB == BA:", np.array_equal(AB, BA), "\n")  # Should be False

# Task 3 - Prove (AB)^T = B^T A^T
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)
print("Task 3 - (AB)^T:\n", AB_T)
print("Task 3 - B^T A^T:\n", B_TA_T)
print("Check if (AB)^T == B^T A^T:", np.array_equal(AB_T, B_TA_T), "\n")  # Should be True

# Task 4 - Solve the system of linear equations using Inverse Method
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using np.linalg.inv
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Task 4 - Solution using inverse method:\n", X)

# Optional: Solve using np.linalg.solve (more efficient)
X_solve = np.linalg.solve(A_eq, B_eq)
print("Task 4 - Solution using np.linalg.solve:\n", X_solve)

Task 1 - A * A^-1:
 [[1. 0.]
 [0. 1.]]
Check if identity:
 True 

Task 2 - AB:
 [[23 13]
 [51 29]]
Task 2 - BA:
 [[36 44]
 [13 16]]
Check if AB == BA: False 

Task 3 - (AB)^T:
 [[23 51]
 [13 29]]
Task 3 - B^T A^T:
 [[23 51]
 [13 29]]
Check if (AB)^T == B^T A^T: True 

Task 4 - Solution using inverse method:
 [ 2.  1. -2.]
Task 4 - Solution using np.linalg.solve:
 [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:

    • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
    and Print the time taken for this operation.

    • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
    this operation.
2. Element-wise Multiplication

    • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
    Measure and Print the time taken for this operation.

    • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
    this operation.
3. Dot Product

    • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
    Print the time taken for this operation.

    • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
    this operation.
4. Matrix Multiplication

    • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

    • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
    Measure and print the time taken for this operation.

In [16]:
import time

In [17]:

size = 1_000_000

# Task 1 - Element-wise Addition
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Task 1 - Python list addition time: {:.5f} seconds".format(end - start))

arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_add = arr1 + arr2
end = time.time()
print("Task 1 - NumPy array addition time: {:.5f} seconds\n".format(end - start))

# Task 2 - Element-wise Multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Task 2 - Python list multiplication time: {:.5f} seconds".format(end - start))

start = time.time()
arr_mul = arr1 * arr2
end = time.time()
print("Task 2 - NumPy array multiplication time: {:.5f} seconds\n".format(end - start))

# Task 3 - Dot Product
start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
print("Task 3 - Python list dot product time: {:.5f} seconds".format(end - start))

start = time.time()
dot_array = np.dot(arr1, arr2)
end = time.time()
print("Task 3 - NumPy array dot product time: {:.5f} seconds\n".format(end - start))

# Task 4 - Matrix Multiplication
matrix_size = 1000
mat1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result_matrix = [[sum(mat1[i][k] * mat2[k][j] for k in range(matrix_size))
                  for j in range(matrix_size)] for i in range(matrix_size)]
end = time.time()
print("Task 4 - Python list matrix multiplication time: {:.5f} seconds".format(end - start))

np_mat1 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size*matrix_size).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.dot(np_mat1, np_mat2)
end = time.time()
print("Task 4 - NumPy array matrix multiplication time: {:.5f} seconds".format(end - start))

Task 1 - Python list addition time: 0.11778 seconds
Task 1 - NumPy array addition time: 0.00419 seconds

Task 2 - Python list multiplication time: 0.12294 seconds
Task 2 - NumPy array multiplication time: 0.00484 seconds

Task 3 - Python list dot product time: 0.15593 seconds
Task 3 - NumPy array dot product time: 0.00184 seconds

Task 4 - Python list matrix multiplication time: 198.10669 seconds
Task 4 - NumPy array matrix multiplication time: 1.92756 seconds
